// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PedrinhoSecretsDKRT.Models;

namespace PedrinhoSecretsDKRT.Migrations
{
    [DbContext(typeof(PedrinhoSecretsDKRTContext))]
    partial class PedrinhoSecretsDKRTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PedrinhoSecretsDKRT.Models.enigmas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("perguntas");

                    b.Property<string>("resposta");

                    b.HasKey("id");

                    b.ToTable("enigmas");
                });
#pragma warning restore 612, 618
        }
    }
}
